name: responsive_image
description: A flutter library that add responsive capabilities to images
version: 1.0.0
author: Théo Champion <contact.theochampion@gmail.com>
homepage: https://github.com/theochampion/responsive_image

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
